In [33]:
import pandas as pd

X_train = pd.read_csv("D:\\360DigiTMG\\DataScience\\17. Machine Learning Classifier Technique - Naive Bayes\\Assignment Q\\SalaryData_Train.csv")
X_train.head()

age          workclass   education  educationno        maritalstatus  \
0   39          State-gov   Bachelors           13        Never-married   
1   50   Self-emp-not-inc   Bachelors           13   Married-civ-spouse   
2   38            Private     HS-grad            9             Divorced   
3   53            Private        11th            7   Married-civ-spouse   
4   28            Private   Bachelors           13   Married-civ-spouse   

           occupation    relationship    race      sex  capitalgain  \
0        Adm-clerical   Not-in-family   White     Male         2174   
1     Exec-managerial         Husband   White     Male            0   
2   Handlers-cleaners   Not-in-family   White     Male            0   
3   Handlers-cleaners         Husband   Black     Male            0   
4      Prof-specialty            Wife   Black   Female            0   

   capitalloss  hoursperweek          native  Salary  
0            0            40   United-States   <=50K  
1            0            13   United-States   <=50K  
2            0            40   United-States   <=50K  
3            0            40   United-States   <=50K  
4            0            40            Cuba   <=50K

In [34]:
y_train = X_train['Salary']
y_train.columns = 'Salary'
y_train.head()

0     <=50K
1     <=50K
2     <=50K
3     <=50K
4     <=50K
Name: Salary, dtype: object

In [35]:
X_test = pd.read_csv("D:\\360DigiTMG\\DataScience\\17. Machine Learning Classifier Technique - Naive Bayes\\Assignment Q\\SalaryData_Test.csv")
X_test.head()

age   workclass      education  educationno        maritalstatus  \
0   25     Private           11th            7        Never-married   
1   38     Private        HS-grad            9   Married-civ-spouse   
2   28   Local-gov     Assoc-acdm           12   Married-civ-spouse   
3   44     Private   Some-college           10   Married-civ-spouse   
4   34     Private           10th            6        Never-married   

           occupation    relationship    race    sex  capitalgain  \
0   Machine-op-inspct       Own-child   Black   Male            0   
1     Farming-fishing         Husband   White   Male            0   
2     Protective-serv         Husband   White   Male            0   
3   Machine-op-inspct         Husband   Black   Male         7688   
4       Other-service   Not-in-family   White   Male            0   

   capitalloss  hoursperweek          native  Salary  
0            0            40   United-States   <=50K  
1            0            50   United-States   <=50K  
2            0            40   United-States    >50K  
3            0            40   United-States    >50K  
4            0            30   United-States   <=50K

In [36]:
y_test = X_test['Salary']
y_test.columns = 'Salary'
y_test.head()

0     <=50K
1     <=50K
2      >50K
3      >50K
4     <=50K
Name: Salary, dtype: object

In [37]:
X_train.drop(['Salary'], axis=1, inplace=True)
X_test.drop(['Salary'], axis=1, inplace=True)

In [38]:
X_train_object = X_train.select_dtypes('object')
X_train_object.head()

workclass   education        maritalstatus          occupation  \
0          State-gov   Bachelors        Never-married        Adm-clerical   
1   Self-emp-not-inc   Bachelors   Married-civ-spouse     Exec-managerial   
2            Private     HS-grad             Divorced   Handlers-cleaners   
3            Private        11th   Married-civ-spouse   Handlers-cleaners   
4            Private   Bachelors   Married-civ-spouse      Prof-specialty   

     relationship    race      sex          native  
0   Not-in-family   White     Male   United-States  
1         Husband   White     Male   United-States  
2   Not-in-family   White     Male   United-States  
3         Husband   Black     Male   United-States  
4            Wife   Black   Female            Cuba

In [39]:
X_train_num = X_train.select_dtypes(['int64', 'float64'])
X_train_num.head()

age  educationno  capitalgain  capitalloss  hoursperweek
0   39           13         2174            0            40
1   50           13            0            0            13
2   38            9            0            0            40
3   53            7            0            0            40
4   28           13            0            0            40

In [40]:
from sklearn.preprocessing import LabelEncoder

lblenc = LabelEncoder()
X_train_object.workclass = pd.DataFrame(lblenc.fit_transform(X_train_object.workclass))
X_train_object.education = pd.DataFrame(lblenc.fit_transform(X_train_object.education))
X_train_object.maritalstatus = pd.DataFrame(lblenc.fit_transform(X_train_object.maritalstatus))
X_train_object.occupation = pd.DataFrame(lblenc.fit_transform(X_train_object.occupation))
X_train_object.relationship = pd.DataFrame(lblenc.fit_transform(X_train_object.relationship))
X_train_object.race = pd.DataFrame(lblenc.fit_transform(X_train_object.race))
X_train_object.sex = pd.DataFrame(lblenc.fit_transform(X_train_object.sex))
X_train_object.native = pd.DataFrame(lblenc.fit_transform(X_train_object.native))

X_train_object

workclass  education  maritalstatus  occupation  relationship  race  \
0              5          9              4           0             1     4   
1              4          9              2           3             0     4   
2              2         11              0           5             1     4   
3              2          1              2           5             0     2   
4              2          9              2           9             5     2   
...          ...        ...            ...         ...           ...   ...   
30156          2          7              2          12             5     4   
30157          2         11              2           6             0     4   
30158          2         11              6           0             4     4   
30159          2         11              4           0             3     4   
30160          3         11              2           3             5     4   

       sex  native  
0        1      37  
1        1      37  
2        1      37  
3        1      37  
4        0       4  
...    ...     ...  
30156    0      37  
30157    1      37  
30158    0      37  
30159    1      37  
30160    0      37  

[30161 rows x 8 columns]

In [41]:
from sklearn.preprocessing import MinMaxScaler

scl = MinMaxScaler()
X_train_num = pd.DataFrame(scl.fit_transform(X_train_num))
X_train_num

0         1         2    3         4
0      0.301370  0.800000  0.021740  0.0  0.397959
1      0.452055  0.800000  0.000000  0.0  0.122449
2      0.287671  0.533333  0.000000  0.0  0.397959
3      0.493151  0.400000  0.000000  0.0  0.397959
4      0.150685  0.800000  0.000000  0.0  0.397959
...         ...       ...       ...  ...       ...
30156  0.136986  0.733333  0.000000  0.0  0.377551
30157  0.315068  0.533333  0.000000  0.0  0.397959
30158  0.561644  0.533333  0.000000  0.0  0.397959
30159  0.068493  0.533333  0.000000  0.0  0.193878
30160  0.479452  0.533333  0.150242  0.0  0.397959

[30161 rows x 5 columns]

In [42]:
X_train_normalised = pd.concat([X_train_object, X_train_num], axis=1)
X_train_normalised.head()

workclass  education  maritalstatus  occupation  relationship  race  sex  \
0          5          9              4           0             1     4    1   
1          4          9              2           3             0     4    1   
2          2         11              0           5             1     4    1   
3          2          1              2           5             0     2    1   
4          2          9              2           9             5     2    0   

   native         0         1        2    3         4  
0      37  0.301370  0.800000  0.02174  0.0  0.397959  
1      37  0.452055  0.800000  0.00000  0.0  0.122449  
2      37  0.287671  0.533333  0.00000  0.0  0.397959  
3      37  0.493151  0.400000  0.00000  0.0  0.397959  
4       4  0.150685  0.800000  0.00000  0.0  0.397959

In [43]:
X_test_object = X_test.select_dtypes('object')
X_test_object.head()

workclass      education        maritalstatus          occupation  \
0     Private           11th        Never-married   Machine-op-inspct   
1     Private        HS-grad   Married-civ-spouse     Farming-fishing   
2   Local-gov     Assoc-acdm   Married-civ-spouse     Protective-serv   
3     Private   Some-college   Married-civ-spouse   Machine-op-inspct   
4     Private           10th        Never-married       Other-service   

     relationship    race    sex          native  
0       Own-child   Black   Male   United-States  
1         Husband   White   Male   United-States  
2         Husband   White   Male   United-States  
3         Husband   Black   Male   United-States  
4   Not-in-family   White   Male   United-States

In [44]:
X_test_num = X_test.select_dtypes(['int64', 'float64'])
X_test_num.head()

age  educationno  capitalgain  capitalloss  hoursperweek
0   25            7            0            0            40
1   38            9            0            0            50
2   28           12            0            0            40
3   44           10         7688            0            40
4   34            6            0            0            30

In [45]:
from sklearn.preprocessing import LabelEncoder

lblenc = LabelEncoder()
X_test_object.workclass = pd.DataFrame(lblenc.fit_transform(X_test_object.workclass))
X_test_object.education = pd.DataFrame(lblenc.fit_transform(X_test_object.education))
X_test_object.maritalstatus = pd.DataFrame(lblenc.fit_transform(X_test_object.maritalstatus))
X_test_object.occupation = pd.DataFrame(lblenc.fit_transform(X_test_object.occupation))
X_test_object.relationship = pd.DataFrame(lblenc.fit_transform(X_test_object.relationship))
X_test_object.race = pd.DataFrame(lblenc.fit_transform(X_test_object.race))
X_test_object.sex = pd.DataFrame(lblenc.fit_transform(X_test_object.sex))
X_test_object.native = pd.DataFrame(lblenc.fit_transform(X_test_object.native))

X_test_object

workclass  education  maritalstatus  occupation  relationship  race  \
0              2          1              4           6             3     2   
1              2         11              2           4             0     4   
2              1          7              2          10             0     4   
3              2         15              2           6             0     2   
4              2          0              4           7             1     4   
...          ...        ...            ...         ...           ...   ...   
15055          2          9              4           9             3     4   
15056          2          9              0           9             1     4   
15057          2          9              2           9             0     4   
15058          2          9              0           0             3     1   
15059          3          9              2           3             0     4   

       sex  native  
0        1      37  
1        1      37  
2        1      37  
3        1      37  
4        1      37  
...    ...     ...  
15055    1      37  
15056    0      37  
15057    1      37  
15058    1      37  
15059    1      37  

[15060 rows x 8 columns]

In [46]:
from sklearn.preprocessing import MinMaxScaler

scl = MinMaxScaler()
X_test_num = pd.DataFrame(scl.fit_transform(X_test_num))
X_test_num

0         1         2    3         4
0      0.109589  0.400000  0.000000  0.0  0.397959
1      0.287671  0.533333  0.000000  0.0  0.500000
2      0.150685  0.733333  0.000000  0.0  0.397959
3      0.369863  0.600000  0.076881  0.0  0.397959
4      0.232877  0.333333  0.000000  0.0  0.295918
...         ...       ...       ...  ...       ...
15055  0.219178  0.800000  0.000000  0.0  0.397959
15056  0.301370  0.800000  0.000000  0.0  0.357143
15057  0.287671  0.800000  0.000000  0.0  0.500000
15058  0.369863  0.800000  0.054551  0.0  0.397959
15059  0.246575  0.800000  0.000000  0.0  0.602041

[15060 rows x 5 columns]

In [47]:
X_test_normalised = pd.concat([X_test_object, X_test_num], axis=1)
X_test_normalised.head()

workclass  education  maritalstatus  occupation  relationship  race  sex  \
0          2          1              4           6             3     2    1   
1          2         11              2           4             0     4    1   
2          1          7              2          10             0     4    1   
3          2         15              2           6             0     2    1   
4          2          0              4           7             1     4    1   

   native         0         1         2    3         4  
0      37  0.109589  0.400000  0.000000  0.0  0.397959  
1      37  0.287671  0.533333  0.000000  0.0  0.500000  
2      37  0.150685  0.733333  0.000000  0.0  0.397959  
3      37  0.369863  0.600000  0.076881  0.0  0.397959  
4      37  0.232877  0.333333  0.000000  0.0  0.295918

In [50]:
from sklearn.naive_bayes import MultinomialNB as MB

classifier_mb = MB()
classifier_mb.fit(X_train_normalised, y_train)
classifier_mb

test_pred = classifier_mb.predict(X_test_normalised)
test_pred

C:\Users\riten\anaconda3\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
C:\Users\riten\anaconda3\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


array([' <=50K', ' <=50K', ' >50K', ..., ' >50K', ' <=50K', ' <=50K'],
      dtype='<U6')

In [51]:
pd.crosstab(test_pred, y_test)

Salary   <=50K   >50K
row_0                
 <=50K    9760   1880
 >50K     1600   1820

In [55]:
import numpy as np
accuracy_test = np.mean(test_pred==y_test)
accuracy_test

0.7689243027888446

In [60]:
# tuning the parameter

classifier_mb_tuned = MB(alpha=5)
classifier_mb_tuned.fit(X_train_normalised, y_train)

test_pred_tuned = classifier_mb_tuned.predict(X_test_normalised)
accuracy_after_tuning = np.mean(test_pred_tuned == y_test)
accuracy_after_tuning

C:\Users\riten\anaconda3\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
C:\Users\riten\anaconda3\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


0.7691235059760956

# Question 2

In [218]:
import pandas as pd

X = pd.read_csv("D:\\360DigiTMG\\DataScience\\17. Machine Learning Classifier Technique - Naive Bayes\\Assignment Q\\NB_Car_Ad.csv")
X.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [219]:
X.describe()

User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

In [220]:
X_num = pd.DataFrame({'Age': X_train['Age'], 'EstimatedSalary': X_train['EstimatedSalary']})
X_num.head()

Age  EstimatedSalary
0   19            19000
1   35            20000
2   26            43000
3   27            57000
4   19            76000

In [221]:
X_object = pd.DataFrame({'Gender': X_train['Gender']})
X_object.head()

Gender
0    Male
1    Male
2  Female
3  Female
4    Male

In [222]:
y = pd.DataFrame({'Purchased': X['Purchased']})
y.Purchased.value_counts()

0    257
1    143
Name: Purchased, dtype: int64

In [223]:
from sklearn.preprocessing import MinMaxScaler

scl = MinMaxScaler()
X_num = pd.DataFrame(scl.fit_transform(X_num))
X_num.head()

0         1
0  0.023810  0.029630
1  0.404762  0.037037
2  0.190476  0.207407
3  0.214286  0.311111
4  0.023810  0.451852

In [224]:
from sklearn.preprocessing import LabelEncoder
enc = LabelEncoder()
X_object.Gender = enc.fit_transform(X_object.Gender)
X_object.head()

Gender
0       1
1       1
2       0
3       0
4       1

In [225]:
X_normalised = pd.concat([X_num, X_object], axis=1)
X_normalised.head()

0         1  Gender
0  0.023810  0.029630       1
1  0.404762  0.037037       1
2  0.190476  0.207407       0
3  0.214286  0.311111       0
4  0.023810  0.451852       1

In [226]:
userId = X['User ID']
userId.head()

0    15624510
1    15810944
2    15668575
3    15603246
4    15804002
Name: User ID, dtype: int64

In [227]:
from sklearn.model_selection import train_test_split

X_normalised_train, X_normalised_test, y_train, y_test = train_test_split(X_normalised, y, test_size=0.2)

In [228]:
X_normalised_train

0         1  Gender
198  0.190476  0.481481       1
382  0.619048  0.918519       0
29   0.309524  0.022222       1
126  0.571429  0.370370       1
355  1.000000  0.140741       1
..        ...       ...     ...
201  0.738095  0.437037       1
93   0.261905  0.096296       0
134  0.238095  0.296296       0
4    0.023810  0.451852       1
312  0.476190  0.259259       0

[320 rows x 3 columns]

In [229]:
y_train

Purchased
198          0
382          1
29           0
126          0
355          1
..         ...
201          0
93           0
134          0
4            0
312          0

[320 rows x 1 columns]

In [230]:
from sklearn.naive_bayes import MultinomialNB as MB

# Multinomial Naive Bayes
classifier_mb = MB()
classifier_mb.fit(X_normalised_train, y_train)

# Evaluation on Test Data
nb_predict = classifier_mb.predict(X_normalised_test)
nb_predict

C:\Users\riten\anaconda3\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
C:\Users\riten\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\riten\anaconda3\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [238]:
pd.crosstab(nb_predict, y_test['Purchased'])

Purchased   0   1
row_0            
0          55  25

In [207]:
from sklearn.metrics import accuracy_score

accuracy_score(nb_predict, y_test)

0.5875

In [239]:
nb_predict_train = classifier_mb.predict(X_normalised_train)
nb_predict_train

C:\Users\riten\anaconda3\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [240]:
pd.crosstab(nb_predict_train, y_train['Purchased'])

Purchased    0    1
row_0              
0          202  118

In [209]:
from sklearn.metrics import accuracy_score

accuracy_score(nb_predict_train, y_train)

0.65625

In [117]:
# Multinomial Naive Bayes
classifier_mb = MB(alpha=5)
classifier_mb.fit(X_normalised_train, y_train)

# Evaluation on Test Data
nb_predict = classifier_mb.predict(X_normalised_test)
nb_predict

C:\Users\riten\anaconda3\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
C:\Users\riten\anaconda3\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

# Question 3

In [143]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer

# import the tweet dataset
X1 = pd.read_csv("D:\\360DigiTMG\\DataScience\\17. Machine Learning Classifier Technique - Naive Bayes\\Assignment Q\\Disaster_tweets_NB.csv")
X1.head()

id keyword location                                               text  \
0   1     NaN      NaN  Our Deeds are the Reason of this #earthquake M...   
1   4     NaN      NaN             Forest fire near La Ronge Sask. Canada   
2   5     NaN      NaN  All residents asked to 'shelter in place' are ...   
3   6     NaN      NaN  13,000 people receive #wildfires evacuation or...   
4   7     NaN      NaN  Just got sent this photo from Ruby #Alaska as ...   

   target  
0       1  
1       1  
2       1  
3       1  
4       1

In [144]:
# dropping the unusual columns
X1.drop(['keyword', 'location', 'id'], axis=1, inplace=True)
X1.head()

text  target
0  Our Deeds are the Reason of this #earthquake M...       1
1             Forest fire near La Ronge Sask. Canada       1
2  All residents asked to 'shelter in place' are ...       1
3  13,000 people receive #wildfires evacuation or...       1
4  Just got sent this photo from Ruby #Alaska as ...       1

In [148]:
# text preprocessing

"""
Here extracting the stopwords from a file

then splitted that and stored as an array
"""
stop_words = []
with open("D:\\360DigiTMG\\DataScience\\0. Personal\\stopwords.txt") as sw:
    stop_words = sw.read()

stop_words = stop_words.split('\n')
stop_words

['a',
 'about',
 'above',
 'across',
 'after',
 'again',
 'against',
 'all',
 'almost',
 'alone',
 'along',
 'already',
 'also',
 'although',
 'always',
 'among',
 'an',
 'and',
 'another',
 'any',
 'anybody',
 'anyone',
 'anything',
 'anywhere',
 'are',
 'area',
 'areas',
 'around',
 'as',
 'ask',
 'asked',
 'asking',
 'asks',
 'at',
 'away',
 'b',
 'back',
 'backed',
 'backing',
 'backs',
 'be',
 'became',
 'because',
 'become',
 'becomes',
 'been',
 'before',
 'began',
 'behind',
 'being',
 'beings',
 'best',
 'better',
 'between',
 'big',
 'both',
 'but',
 'by',
 'c',
 'came',
 'can',
 'cannot',
 'case',
 'cases',
 'certain',
 'certainly',
 'clear',
 'clearly',
 'come',
 'could',
 'd',
 'did',
 'differ',
 'different',
 'differently',
 'do',
 'does',
 'done',
 'down',
 'down',
 'downed',
 'downing',
 'downs',
 'during',
 'e',
 'each',
 'early',
 'either',
 'end',
 'ended',
 'ending',
 'ends',
 'enough',
 'even',
 'evenly',
 'ever',
 'every',
 'everybody',
 'everyone',
 'everything',

In [151]:
# custom function to clean the tweets
import re
def cleanText(i):
    i = re.sub("[^A-Za-z" "]+", " ", i).lower()
    i = re.sub("[0-9" "]+"," ",i)
    words = []
    for w in i.split(" "):
        if w not in stop_words:
            words.append(w)
    return " ".join(words)

cleanText("Hi my name is Ritendu Bhattacharyya")

'hi name ritendu bhattacharyya'

In [153]:
X1.text = X1.text.apply(cleanText)
X1.head()

text  target
0              deeds reason earthquake allah forgive       1
1              forest fire near la ronge sask canada       1
2  residents shelter notified officers evacuation...       1
3     people receive wildfires evacuation california       1
4  sent photo ruby alaska smoke wildfires pours s...       1

In [155]:
from sklearn.model_selection import train_test_split

X1_train, X1_test = train_test_split(X1, test_size=0.2)

In [172]:
# custom function to split into words 
def split_words(w):
    return w.split(" ")

X1_bow = CountVectorizer(analyzer=split_words).fit(X1.text)

X1_all_bow_matrix = X1_bow.transform(X1.text)
X1_train_bow_matrix = X1_bow.transform(X1_train.text)
X1_test_bow_matrix = X1_bow.transform(X1_test.text)

tfidf = TfidfTransformer().fit(X1_all_bow_matrix)
tfidf_train = tfidf.transform(X1_train_bow_matrix)
tfidf_test = tfidf.transform(X1_test_bow_matrix)

In [173]:
# creating navie_bayes model
from sklearn.naive_bayes import MultinomialNB as MB

mb = MB()
mb.fit(tfidf_train, X1_train.target)

test_predict_mb = mb.predict(tfidf_test)
test_predict_mb

array([1, 0, 1, ..., 1, 0, 0], dtype=int64)

In [177]:
# accuracy checks
from sklearn.metrics import accuracy_score as score
score(X1_test.target, test_predict_mb)

0.7892317793827971

In [181]:
pd.crosstab(test_predict_mb, X1_test.target)

target    0    1
row_0           
0       786  227
1        94  416

In [178]:
train_predict_mb = mb.predict(tfidf_train)
train_predict_mb

array([1, 0, 1, ..., 1, 0, 1], dtype=int64)

In [179]:
# accuracy checks
from sklearn.metrics import accuracy_score as score
score(X1_train.target, train_predict_mb)

0.9251231527093596

In [182]:
pd.crosstab(train_predict_mb, X1_train.target)

target     0     1
row_0             
0       3390   384
1         72  2244

In [193]:
# creating navie_bayes model with tunning parameter
from sklearn.naive_bayes import MultinomialNB as MB

mb = MB(alpha=2)
mb.fit(tfidf_train, X1_train.target)

test_predict_mb = mb.predict(tfidf_test)
test_predict_mb

array([1, 0, 1, ..., 1, 0, 0], dtype=int64)

In [194]:
score(X1_test.target, test_predict_mb)

0.7918581746552856